[project]
name = "gemma-9b-mk"
version = "1.8.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gemma>=1.2.2",
    "kagglehub>=0.3.6",
    "numpy>=2.2.1",
    "sentencepiece>=0.2.0",
    "torch>=2.5.1",
    "transformers>=4.47.1",
]
